version: '3.8'

services:


#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0.2
#    container_name: keycloak1
#    volumes:
#      - ./providers:/opt/keycloak/providers
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    ports:
#      - "8082:8080"
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    command: start-dev

  keycloak:
    image: bitnami/keycloak:21.0.2
    container_name: keycloak3
    depends_on:
      - keycloak-postgres
    environment:
      KEYCLOAK_DATABASE_HOST: keycloak-postgres
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8085:8080"

  keycloak-postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: bitnami_keycloak
      POSTGRES_USER: bn_keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data



volumes:
  keycloak_postgres_data: